# Generated by Django 5.0.3 on 2024-03-31 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rooms_count', models.IntegerField()),
                ('windows_for_rooms', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Windows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_number', models.TextField()),
                ('data', models.TextField()),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wins', to='api.date')),
            ],
        ),
    ]
